name: Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Installing node dependencies..."
          npm i
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Building...
        run: |
          echo "Building project..."
          npm run build
        env:
          CI: true
          EXTERN_API_HOSTNAME: https://api.robertify.me
          EXTERN_API_MASTER_PASSWORD: ${{ secrets.HOSTED_API_MASTER_PASSWORD }}