name: Build Pipeline

on:
  push:
    branches: [main]
  test_pull_request:
      branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          echo "Installing node dependencies..."
          npm i
      - name: Linting...
        run: |
          echo "Linting project..."
          npm run lint
        env:
          CI: true
  build:
    name: Build
    runs-on: debian-latest
    needs: [lint]
    steps:
      - name: Building...
        run: |
          echo "Building project..."
          npm run build
        env:
          CI: true